#
# _config.yml for noah.marcuse.ink
#

exclude: [ "CNAME", "README.md", "LICENSE.txt", "UNLICENSE.txt", "tmp", "*.sh", "**/*_src*" ]
permalink: /blog/:year/:month/:day/:title.:output_ext
production_url: https://noah.marcuse.ink
title: Noah Marcuse
markdown: kramdown
plugins:
  - jekyll-redirect-from
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

google_analytics_id: LATER
google_validation: LATER
alexa_validation: LATER
bing_validation: LATER
